// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManager.Server.Data;

#nullable disable

namespace StudentManager.Server.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20240623024349_Add Students ")]
    partial class AddStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedLibrary.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0ee8ac8-bc05-4bd1-a96d-61bd16c0614b"),
                            Class = "4A",
                            Email = "alice.dupont@collegesjb.com",
                            Name = "Alice Dupont"
                        },
                        new
                        {
                            Id = new Guid("78ee9f65-9a9b-4efb-a15e-24b9a182f7e3"),
                            Class = "5B",
                            Email = "marc.durand@collegesjb.com",
                            Name = "Marc Durand"
                        },
                        new
                        {
                            Id = new Guid("f1977078-d508-4a6a-b0fb-07435d3b80b0"),
                            Class = "3C",
                            Email = "julie.martin@collegesjb.com",
                            Name = "Julie Martin"
                        },
                        new
                        {
                            Id = new Guid("4baa3bdc-4994-4290-9f2b-10b8d0bbae09"),
                            Class = "2D",
                            Email = "pierre.dubois@collegesjb.com",
                            Name = "Pierre Dubois"
                        },
                        new
                        {
                            Id = new Guid("3e57428b-2a9b-4d65-aa74-35d42342ca2d"),
                            Class = "1A",
                            Email = "sophie.lefevre@collegesjb.com",
                            Name = "Sophie Lefevre"
                        },
                        new
                        {
                            Id = new Guid("216c635f-8d1e-4f60-9fac-f94774fe0a31"),
                            Class = "4B",
                            Email = "paul.moreau@collegesjb.com",
                            Name = "Paul Moreau"
                        },
                        new
                        {
                            Id = new Guid("80726ec6-8ac2-4134-b964-7ab5a4d47b5a"),
                            Class = "5C",
                            Email = "lucie.petit@collegesjb.com",
                            Name = "Lucie Petit"
                        },
                        new
                        {
                            Id = new Guid("e09519f0-735d-4f85-95f5-f564e5b2fae9"),
                            Class = "3A",
                            Email = "thomas.richard@collegesjb.com",
                            Name = "Thomas Richard"
                        },
                        new
                        {
                            Id = new Guid("12365773-3c0c-412a-9310-4d4ff5f2c28c"),
                            Class = "2B",
                            Email = "emma.michel@collegesjb.com",
                            Name = "Emma Michel"
                        },
                        new
                        {
                            Id = new Guid("732929b4-52a3-4a88-b01e-6216fe245c4f"),
                            Class = "1C",
                            Email = "antoine.leroy@collegesjb.com",
                            Name = "Antoine Leroy"
                        },
                        new
                        {
                            Id = new Guid("5fef2dc4-f057-4870-9f49-04cf532898ef"),
                            Class = "4C",
                            Email = "claire.roux@collegesjb.com",
                            Name = "Claire Roux"
                        },
                        new
                        {
                            Id = new Guid("152af75b-e25d-4a03-a8f5-7c2161293e31"),
                            Class = "5A",
                            Email = "julien.vincent@collegesjb.com",
                            Name = "Julien Vincent"
                        },
                        new
                        {
                            Id = new Guid("678bf73e-dd68-47d3-9e86-be0dd9448b4d"),
                            Class = "3B",
                            Email = "manon.garnier@collegesjb.com",
                            Name = "Manon Garnier"
                        },
                        new
                        {
                            Id = new Guid("4f8b41b1-eaab-476b-b059-d6295aa3eea4"),
                            Class = "2C",
                            Email = "nicolas.lambert@collegesjb.com",
                            Name = "Nicolas Lambert"
                        },
                        new
                        {
                            Id = new Guid("abacf5de-d7a4-4c01-a5ee-091bf9e39ada"),
                            Class = "1B",
                            Email = "elodie.fournier@collegesjb.com",
                            Name = "Elodie Fournier"
                        },
                        new
                        {
                            Id = new Guid("7af00511-ffd0-441a-a24d-7f72e556ded4"),
                            Class = "4D",
                            Email = "mathieu.chevalier@collegesjb.com",
                            Name = "Mathieu Chevalier"
                        },
                        new
                        {
                            Id = new Guid("7102fe8e-9b84-491b-83fa-ee28a2b548ba"),
                            Class = "5D",
                            Email = "isabelle.francois@collegesjb.com",
                            Name = "Isabelle Francois"
                        },
                        new
                        {
                            Id = new Guid("21a975b0-7dd8-4502-ba9d-e51f3c825ffd"),
                            Class = "3D",
                            Email = "hugo.dupuis@collegesjb.com",
                            Name = "Hugo Dupuis"
                        },
                        new
                        {
                            Id = new Guid("a7a023b2-df66-4c67-9a03-9d7c677abfc1"),
                            Class = "2A",
                            Email = "camille.fontaine@collegesjb.com",
                            Name = "Camille Fontaine"
                        },
                        new
                        {
                            Id = new Guid("1e8d9c2f-a2f0-40f4-a743-ac3a13d2fba8"),
                            Class = "1D",
                            Email = "victor.leger@collegesjb.com",
                            Name = "Victor Leger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
